export const reviewPage = `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Release Operations · Revisión local</title><link rel="stylesheet" href="/style.css"></head>
<body><header><span class="brand">◈ RELEASE OPERATIONS</span><span class="tag">LOCAL · REVISIÓN EXPLÍCITA</span></header>
<main><section class="hero"><p class="eyebrow">CONTROL DE CAMBIOS</p><h1>Revisa el cambio.<br>Observa cada paso.</h1><p>La aprobación local autoriza este plan. Las aprobaciones de Azure se gestionan por separado.</p></section>
<section id="message" role="status"></section><div class="layout"><aside><h2>Operaciones</h2><div id="history"></div><button id="refresh">Actualizar</button></aside><article id="detail"><p>Selecciona una operación del historial o prepara una desde Copilot.</p></article></div></main><footer>Las credenciales permanecen en el servidor. Cerrar esta ventana no cancela un despliegue.</footer><script src="/app.js"></script></body></html>`;
export const reviewStyle = `button:disabled{opacity:.5;cursor:not-allowed}:root{font-family:system-ui,sans-serif;color:#172a35;background:#f3f5f4}*{box-sizing:border-box}body{margin:0}header{display:flex;justify-content:space-between;padding:24px 5%;background:#112e38;color:white}.brand{font-weight:800;letter-spacing:.1em}.tag,.eyebrow{font-size:12px;letter-spacing:.14em}main{max-width:1200px;margin:auto;padding:36px 24px}.hero{margin-bottom:32px}h1{font-size:clamp(30px,5vw,48px);line-height:1.12;margin:12px 0}.hero p{max-width:680px;color:#50616a}.eyebrow{color:#187867!important;font-weight:800}.layout{display:grid;grid-template-columns:250px 1fr;gap:24px}article,aside{background:white;border:1px solid #dce3df;border-radius:16px;padding:24px;min-width:0}h2{font-size:20px}h3{font-size:15px;margin-top:28px}.row{display:flex;justify-content:space-between;gap:16px;border-bottom:1px solid #eee;padding:12px 0}.value{font-weight:650;overflow-wrap:anywhere;text-align:right}.badge{background:#e4f3ed;color:#176b57;padding:6px 12px;border-radius:24px;display:inline-block;font-size:13px}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{text-align:left;padding:12px 6px;border-bottom:1px solid #e5e9e7;overflow-wrap:anywhere;font-size:13px}button{border:1px solid #b8c9c0;border-radius:8px;padding:11px 14px;background:white;color:#174838;cursor:pointer;margin:5px 6px 5px 0;font-weight:650}button.primary{background:#127460;color:white;border:0}button:disabled{opacity:.5;cursor:wait}.history{display:block;width:100%;text-align:left}.notice{padding:14px;border-radius:10px;background:#fff1d9;color:#755117;margin:14px 0}.event{border-left:2px solid #81b6a2;padding:8px 14px;margin-left:6px}.event time{font-size:11px;color:#61726b;display:block}input,textarea{width:100%;padding:10px;border:1px solid #b8c9c0;border-radius:6px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f2f5f3;padding:12px;font-size:12px}footer{text-align:center;padding:30px;color:#61726b;font-size:12px}@media(max-width:720px){.layout{grid-template-columns:1fr}header{gap:20px}.tag{display:none}}`;
export const reviewScript = `let token=new URLSearchParams(location.hash.slice(1)).get('token')||sessionStorage.getItem('reviewToken');
let selected=new URLSearchParams(location.hash.slice(1)).get('id');if(token)sessionStorage.setItem('reviewToken',token);history.replaceState(null,'',location.pathname);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const msg=document.getElementById('message');let acting=false;let lastVersion='';
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.message||'Error de operación');return data;}
async function action(name,body={}){if(acting)return;acting=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{const out=await api('executions/'+selected+'/'+name,body);if(out.id&&name==='rollback')selected=out.id;lastVersion='';await load();}catch(e){msg.textContent=e.message;msg.className='notice';}finally{acting=false;document.getElementById('refresh').disabled=false;lastVersion='';await load();}}
function button(text,fn,cls){const b=el('button',text,cls);b.onclick=fn;b.disabled=acting;return b;}
const labels={planned:'Pendiente de revisión',writing:'Guardando variables',variablesUpdated:'Variables verificadas',requestingDeployment:'Solicitando redeploy',tracking:'Siguiendo despliegue',awaitingApproval:'Esperando aprobación Azure',succeeded:'Despliegue completado',failed:'Finalizado con incidencias',conflict:'Plan desactualizado',uncertain:'Requiere reconciliación',interrupted:'Ejecución interrumpida',trackingTimedOut:'Tiempo de seguimiento agotado',cancelled:'Plan cancelado'};
function applyButton(r){const b=button(r.capabilities?.writesEnabled?'Aplicar cambios y solicitar redeploy':'Escrituras deshabilitadas',()=>action('apply'),'primary');b.disabled=acting||!r.capabilities?.writesEnabled;return b;}
function render(r){const area=document.getElementById('detail');area.replaceChildren();area.append(el('span',labels[r.state]||r.state,'badge'),el('h2',r.operation+' · '+r.mode));
for(const [k,v] of [['Organización / proyecto',r.target.organization+' / '+r.target.project],['Release',r.releaseName+' · '+r.releaseId],['Definition ID',String(r.target.definitionId)],['Escrituras',r.capabilities?.writesEnabled?'Habilitadas':'Deshabilitadas'],['Aprobaciones',r.policy.approvals],['Stage',r.environmentName+' · '+r.environmentId],['Intento esperado',String(r.expectedAttempt)],['Plan válido hasta',new Date(r.expiresAt).toLocaleString()]]){const row=el('div',undefined,'row');row.append(el('span',k),el('span',v,'value'));area.append(row);}
for(const w of r.warnings||[]){const warning=el('section',undefined,'notice');warning.setAttribute('role','alert');warning.append(el('strong','Advertencia · '+w.code),el('p',w.message),el('p',(w.stages||[]).map(s=>s.name+' · '+s.id).join(', ')));area.append(warning);}
if(r.changes.some(d=>d.scope==='release'&&JSON.stringify(d.before)!==JSON.stringify(d.after)))area.append(el('p','Hay cambios globales del release: pueden afectar futuras ejecuciones de otros stages de esta instancia.','notice'));
area.append(el('h3','Variables · estado anterior y propuesto'));const table=el('table');const head=el('tr');for(const x of ['Variable / ámbito','Anterior','Propuesto'])head.append(el('th',x));table.append(head);for(const d of r.changes){const row=el('tr');row.append(el('td',d.name+' / '+d.scope+(JSON.stringify(d.before)===JSON.stringify(d.after)?' · Sin cambios':'')),el('td',d.before===null?'No existía':d.before.value),el('td',d.after===null?'Eliminar':d.after.value));table.append(row);}area.append(table);
area.append(el('h3','Artefactos conservados'));for(const a of r.artifacts){const v=a.definitionReference||{};area.append(el('p',(a.alias||'Artefacto')+' · '+(v.version?.name||v.version?.id||'Versión registrada')+' · '+(v.branch?.id||a.type||'')));}
const link=el('a','Abrir release en Azure');link.href='https://dev.azure.com/'+encodeURIComponent(r.target.organization)+'/'+encodeURIComponent(r.target.project)+'/_releaseProgress?releaseId='+r.releaseId;link.target='_blank';link.rel='noopener noreferrer';area.append(link);
if(r.state==='planned'){area.append(el('p',r.changes.every(d=>JSON.stringify(d.before)===JSON.stringify(d.after))?'Los valores ya coinciden. Se solicitará solo el redeploy, sin actualizar variables. El motor revalidará el plan.':'Este botón guarda las variables y solicita el redeploy del stage indicado. El motor revalidará el plan antes de escribir.','notice'),applyButton(r),button('Cancelar plan',()=>action('cancel')));}
if(r.approvals.length){area.append(el('h3','Aprobaciones de Azure'));for(const a of r.approvals){area.append(el('p',a.approver+' · '+a.approvalType+' · aprobación '+a.id));if(r.policy.approvals==='explicit'&&r.capabilities?.approvalsEnabled){const comment=el('textarea');comment.placeholder='Comentario requerido para la decisión';comment.maxLength=1000;area.append(comment,button('Aprobar despliegue',()=>action('approval',{approvalId:a.id,decision:'approved',comment:comment.value})),button('Rechazar',()=>action('approval',{approvalId:a.id,decision:'rejected',comment:comment.value})));}}}
if(['succeeded','failed'].includes(r.state))area.append(button('Preparar restauración y redeploy',()=>action('rollback')));
if(['uncertain','interrupted','trackingTimedOut'].includes(r.state)){area.append(el('p','Revisa en Azure qué ocurrió y espera a que no haya despliegues activos. Reconocer la revisión libera el bloqueo local; no cancela ni revierte nada.','notice'),button('He reconciliado el estado en Azure',()=>{if(confirm('¿Revisaste el intento en Azure y confirmaste que es seguro liberar el bloqueo local?'))action('recover');}));}
if(r.lastMutation)area.append(el('p','Última solicitud de escritura: '+r.lastMutation));if(r.observabilityError)area.append(el('p','Visibilidad de aprobaciones: '+r.observabilityError.code+'. El seguimiento del intento continúa.','notice'));if(r.observedAttempt!==undefined)area.append(el('p','Intento observado: '+r.observedAttempt));if(r.error)area.append(el('p',r.error.code+': '+r.error.message,'notice'));area.append(el('h3','Historial'));for(const e of r.events){const n=el('div',e.message,'event');n.prepend(el('time',new Date(e.at).toLocaleString()));area.append(n);}}
async function load(){try{const rows=await api('executions');const h=document.getElementById('history');h.replaceChildren();for(const r of rows)h.append(button(r.releaseName+' · '+(labels[r.state]||r.state),()=>{selected=r.id;lastVersion='';load();},'history'));if(!selected&&rows[0])selected=rows[0].id;if(selected){const r=await api('executions/'+selected);const v=JSON.stringify(r);if(v!==lastVersion){render(r);lastVersion=v;}}}catch(e){msg.textContent=e.message;msg.className='notice';}}
document.getElementById('refresh').onclick=load;load();setInterval(()=>{load();},4000);`;
